#	$OpenBSD: pf.conf,v 1.55 2017/12/03 20:40:04 sthen Exp $
# See pf.conf(5) and /etc/examples/pf.conf

# Macros & Options
dns_server = "9.9.9.9"
set skip on lo

# Translation Rules (NAT must come before filtering rules)
match out on egress from 100.64.0.0/10 to any nat-to (egress)

# Filter Policy
block return	# block stateless traffic
pass		# establish keep-state

# Redirect DNS requests coming from the VM to Quad9
pass in proto { udp tcp } from 100.64.0.0/10 to any port domain rdr-to $dns_server port domain

# By default, do not permit remote connections to X11
block return in on ! lo0 proto tcp to port 6000:6010

# Port build user does not need network
block return out log proto {tcp udp} user _pbuild

pass in on tap0 proto tcp from 100.64.1.3 to 100.64.1.2 port 11025

